### ISSUE TITLE
Error with mongoose 4.11.6

### ISSUE THREAD

**Issue by truca** [Vnkitaev/mongoose-float#1]
I had a problem with this package while using mongoose@4.11.6:

/node_modules/mongoose-float/lib/index.js:26
	mongoose.SchemaTypes.Float = mongoose.Types.Float = floatType;
	                                                  ^
TypeError: Cannot set property 'Float' of undefined

I solved it using mongoose@4.11.0

**Comment by dodo360** [comment]
@truca fixed in 1.0.4
